name: Part Inventory and Order Services
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: part_inventory_db
#    ports:
#      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  part-inventory-service:
    image: ram1uj/part-inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: part_inventory_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  part-order-service:
    image: ram1uj/part-order-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: part_inventory_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      INVENTORY_SERVICE_URL: http://part-inventory-service:8080
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - part-inventory-service

volumes:
  mysql_data: